### ISSUE TITLE
视频地址解析始终出错

### ISSUE THREAD

**Issue by OneForward** [Zhangzijing/Meloduet-Bilibili-Video-Fetcher#2]
好像下载 蒂姆伯顿的  《大眼睛》 啊
可是视频地址始终不能解析出来欸
http://www.bilibili.com/video/av3378109/index_13.html
话说demo也失败了欸

**Comment by EwigMidori** [comment]
怀疑之前的apikey方式失效了，还有另一种方案可用，请等待我有时间修复。

**Comment by EwigMidori** [comment]
demo疑似访问频率过高导致服务器IP被封

**Comment by EwigMidori** [comment]
重新发布了桌面应用版本, 详见:
https://github.com/Meloduet/Wpf-BilibiliVideoFetcher
